/**
 * @aicolab/ui-solid — shared Solid v2 UI primitives + token contract.
 *
 * Extracted from solid-playground's COMMONS dashboard. Apps define the
 * semantic --color-* family/content palette and font roles on a theme root
 * (see styles.css for the contract) and import the structural stylesheet:
 *
 *   @import "@aicolab/ui-solid/styles.css";
 *   @source "<relative path to>/packages/ui-solid/src";
 */

export {
	addMonths,
	daysInMonth,
	firstWeekday,
	fmtRange,
	fmtTime,
	longWeekday,
	MONTHS,
	MonthCalendar,
	monthCells,
	monthIndex,
	sameDay,
	todayYMD,
	WEEKDAYS,
	weekdayOf,
	type YM,
	type YMD,
} from './calendar'
export { dismissOnOutside, Field, IconButton, Segmented, type SegOption } from './controls'
export { type FacetItem, Facets, type FacetTabStyle } from './facets'
export {
	Accordion,
	type AccordionDensity,
	AccordionItem,
	type AccordionSpacing,
	Carousel,
	type DocsNavItem,
	DocsShell,
	type Feature,
	FeatureGrid,
	LogoCloud,
	type LogoItem,
	Mark,
	PageHero,
	Section,
	type Step,
	Steps,
} from './marketing'
export { type DropEntry } from './atoms/dropzone'
export {
	ApplicationHeader,
	Callout,
	ColumnMapper,
	type ColumnMapperColumn,
	type ColumnMapperPatch,
	type ColumnMapperRole,
	Combobox,
	DataGrid,
	type DataGridCell,
	type DataGridCellKind,
	type DataGridChild,
	type DataGridColumn,
	type DataGridRow,
	EmptyState,
	ListEditor,
	Menu,
	MenuItem,
	MenuSeparator,
	type MenuTriggerWiring,
	type ThemeMode,
	ThemeToggle,
	themeBootScript,
	ToggleGroup,
	type ToggleOption,
	ToolPanel,
	ToolPanelActions,
	ToolPanelList,
	ToolPanelSection,
	TreeEditor,
	type TreeEditorNode,
	UploadList,
	type UploadListItem,
	type UploadListStatus,
} from './molecules'
export { RichList, RichListItem, RichListMetadata } from './molecules/rich-list'
export {
	ActivityFeed,
	type ActivityFeedItem,
	AdaptiveModalSheet,
	ArtifactCard,
	BottomNavigation,
	BottomNavigationCentreContent,
	type BottomNavigationItem,
	CommandPalette,
	type CommandPaletteItem,
	CommandPaletteTrigger,
	openCommandPalette,
	FlowMap,
	type FlowMapEdge,
	type FlowMapFooter,
	type FlowMapFooterItem,
	type FlowMapNode,
	type FlowMapRail,
	type InspectorDetent,
	InspectorHeader,
	RadialMenu,
	type RadialMenuItem,
	RaisedSheet,
	ResponsiveInspector,
	SceneStage,
	type SceneStageAdapter,
	type SceneStageController,
	type SceneStageMountContext,
	dismissToast,
	toast,
	ToastHost,
	type ToastOptions,
	WorkspaceNavigation,
	WorkspaceNavigationGroup,
	WorkspaceNavigationItem,
	WorkspaceNavigationList,
	WorkspaceShell,
	WorkspaceStage,
	WorkspaceStageTooltip,
} from './organisms'
export { DatePicker, TimePicker } from './pickers'
export {
	AttributionMark,
	AttributionSwatch,
	Avatar,
	AvatarStack,
	type AvatarStackPerson,
	attributionColor,
	Breadcrumb,
	type BreadcrumbItem,
	Button,
	ButtonLink,
	Checkbox,
	Chip,
	Counter,
	Dropzone,
	createAttributionColor,
	createResolvedAttributionColor,
	Eyebrow,
	HoldButton,
	Meter,
	Notice,
	NumberInput,
	Panel,
	Presence,
	PresenceSwatch,
	presenceColor,
	presenceSelectionColor,
	RangeInput,
	Rule,
	resolvePresenceColor,
	resolvePresenceRole,
	QrCode,
	qrSvgString,
	type QrSvgOptions,
	SelectControl,
	Sparkline,
	Spinner,
	StageHint,
	StatusDot,
	type StatusVisual,
	Switch,
	TextArea,
	TextInput,
	VisuallyHidden,
	Waveform,
} from './primitives'
export {
	type ClassProp,
	type ColorBase,
	type ColorLevel,
	type ColorTreatmentProps,
	colorTreatmentData,
	type Variant,
} from './shared/color-treatment'
export {
	defineKnobs,
	type KnobProps,
	type KnobSpec,
	type KnobSyntax,
	mergeKnobStyle,
	type UiColor,
	type UiLength,
	type UiLengthPercentage,
} from './shared/knobs'

export { withScopedViewTransition, withViewTransition } from './vt'
