/** Compatibility façade for modular marketing components. */
export { PageHero } from './molecules/page-hero'
export { Section } from './molecules/section'
export { Mark } from './atoms/mark'
export { type Feature, FeatureGrid } from './molecules/feature-grid'
export { type Step, type StepNodeSize, Steps } from './molecules/steps'
export { LogoCloud, type LogoItem } from './molecules/logo-cloud'
export { AccordionItem, AccordionItemContext, type AccordionItemContextValue, accordionItemKnobs } from './atoms/accordion-item'
export { Accordion, type AccordionDensity, type AccordionSpacing } from './molecules/accordion'
export { Carousel } from './molecules/carousel'
export { type DocsNavItem, DocsShell } from './organisms/docs-shell'
