/** Compatibility façade; implementations are colocated under ./primitives. */
export {
	AccordionItem,
	AccordionItemContext,
	type AccordionItemContextValue,
	accordionItemKnobs,
	attributionColor,
	AttributionMark,
	AttributionSwatch,
	Avatar,
	AvatarStack,
	type AvatarStackPerson,
	Breadcrumb,
	type BreadcrumbItem,
	Button,
	ButtonLink,
	Checkbox,
	Chip,
	type ClassProp,
	type ColorBase,
	type ColorLevel,
	colorTreatmentData,
	type ColorTreatmentProps,
	Counter,
	createAttributionColor,
	createResolvedAttributionColor,
	type DropEntry,
	Dropzone,
	Eyebrow,
	Field,
	HoldButton,
	IconButton,
	Mark,
	Meter,
	Notice,
	NumberInput,
	Panel,
	Presence,
	presenceColor,
	presenceSelectionColor,
	PresenceSwatch,
	QrCode,
	type QrSvgOptions,
	qrSvgString,
	RangeInput,
	resolvePresenceColor,
	resolvePresenceRole,
	Rule,
	Segmented,
	type SegOption,
	SelectControl,
	Sparkline,
	Spinner,
	StageHint,
	StatusDot,
	type StatusVisual,
	Switch,
	TextArea,
	TextInput,
	textInputKnobs,
	type Variant,
	VisuallyHidden,
	Waveform,
} from './primitives/index'
