/** Compatibility façade for the Atomic Design source layout. */
export { type ClassProp, type ColorBase, type ColorLevel, colorTreatmentData, type ColorTreatmentProps, type Variant } from '../shared/color-treatment'
export {
	AccordionItem,
	AccordionItemContext,
	type AccordionItemContextValue,
	accordionItemKnobs,
	attributionColor,
	AttributionMark,
	AttributionSwatch,
	Avatar,
	Breadcrumb,
	type BreadcrumbItem,
	Button,
	ButtonLink,
	Checkbox,
	Chip,
	Counter,
	createAttributionColor,
	createResolvedAttributionColor,
	type DropEntry,
	Dropzone,
	Eyebrow,
	Field,
	HoldButton,
	IconButton,
	Mark,
	Meter,
	Notice,
	NumberInput,
	Panel,
	Presence,
	presenceColor,
	presenceSelectionColor,
	PresenceSwatch,
	QrCode,
	type QrSvgOptions,
	qrSvgString,
	RangeInput,
	resolvePresenceColor,
	resolvePresenceRole,
	Rule,
	Segmented,
	type SegOption,
	SelectControl,
	Sparkline,
	Spinner,
	StageHint,
	StatusDot,
	type StatusVisual,
	Switch,
	TextArea,
	TextInput,
	textInputKnobs,
	VisuallyHidden,
	Waveform,
} from '../atoms'
export { AvatarStack, type AvatarStackPerson } from '../molecules'
